version: "3.8"

services:
    db:
        image: mysql:latest
        container_name: jwt-login-db
        restart: always
        environment:
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DATABASE}
        ports:
            - "${DB_PORT}:${DOCKER_DB_PORT}"
