version: "3.8"

services:
    db:
        image: mysql:latest
        container_name: my-mysql-db
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DATABASE}
        ports:
            - "3307:3306"
